### PR TITLE
Design tokens for Utility Menu

### PR DESCRIPTION
**Pull request by mariannuar**
## Summary
Design tokens for the new Utility Menu component 

## How to review this pull request
- [ ] To review, confirm that Utility Menu component exists and it has design tokens in [Emulsify UI Kit](https://www.figma.com/design/TuQAuw81mBRsaepz2HP7BX/Emulsify-UI-Kit?node-id=24005-354&t=yVklosJfPf7gc4yF-4)

### CODE REVIEW

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@mariannuar Similar to your tooltip PR. Can you switch this to the `convert-components-to-sdc` branch and verify only the changes to the currently listed files apply? I'm guessing you may also run into a lot of unintended files changes as well.

**Review by robherba — APPROVED** [review]
Hey Mari, it looks really good! Great job!

**Comment by mariannuar** [comment]
@robherba Can you help me with a review please?

**Review by callinmullaney — APPROVED** [review]
:shipit:

**Pull request merged**
