### PR TITLE
Compound 1.10.6

### LINKED ISSUE #33: Merge in all of the components from the 1.10.6 release of Compound
Merge in all of the components from the [1.10.6 release of Compound](https://github.com/emulsify-ds/compound/releases/tag/1.10.6).

## Success criteria
- [ ] Code for all the components in Compound is in this repo.
- [ ] Storybook displays all the components in the order provided in this repo, e.g. full pages at the top and tokens at the bottom.

### PR DESCRIPTION
**Pull request by amazingrando**
**What:**

Adds all of the components as-is from Compound 1.10.6 and resolves #33.

**Why:**

Adding these components brings us to parity with Compound and gives us a start on the next steps towards accomplishing the beta version.

**How:**

* The components were mainly copied/pasted over.
* Linting for the UI kit uses @fourkitchens/eslint-config-and-other-formatting and some updates had to be made.

**To Test:**

_The components were brought over as-is. They will be updated over time to integrate with design tokens._

- [ ] Download, run `npm i`, then `npm run develop`
- [ ] Confirm that the sidebar is listed in the order shown on the image below.
- [ ] Check out the components and confirm there are no issues.

CleanShot 2023-02-10 at 14 23 06@2x

### CODE REVIEW

**Comment by ryanhagerty** [comment]
@amazingrando 

I'm seeing a few issues on my end:
* During install, I get an error related to `https://npm.pkg.github.com/download/@fourkitchens/eslint-config-and-other-formatting/` - `401 Unauthorized User cannot be authenticated with the token provided.`
* Attempting to run `develop`: `'sh: concurrently: command not found' ` - this package probably isn't included in the UI kit, so adding it will likely fix the error.

I looked at the Netlify link to compare components since I couldn't get it running:
* I noticed a lot issues related to OS level dark theme settings. I'm guessing this is a feature of Compound but hasn't worked its way in yet. It's mainly dealing with background and text, so Card with Background, Radio Buttons, etc. all have either white text on white backgrounds or dark text on dark backgrounds.
* The accordion buttons aren't inheriting compounds basic resets
* Icons don't work

**Screenshots**
Screen Shot 2023-02-16 at 1 06 34 PM
Screen Shot 2023-02-16 at 1 06 47 PM
33dbbfb-35aa-4232-b856-72be1ddef059.png)

**Review by ryanhagerty — CHANGES_REQUESTED** [review]
See general comment

**Comment by callinmullaney** [comment]
@amazingrando This PR seems fine to merge but I want to acknowledge @ryanhagerty feedback as valid. 
1. I was able to get this to build locally but I needed to add `export FOUR_KITCHENS_BUILD_TOKEN=[my github account token]` to my computer `~/.zshrc` file. After that it was able to build and `npm run develop` just fine. We should consider publishing that eslint to npm and avoiding this step altogether or consider a different approach to handling that external repo. (out of scope for this PR)
2. I'm running Ubuntu 22.04 and the UI kit isn't respecting my OS level dark mode either. I think we can deal with this by refactoring the existing `color` component and using `@media (prefers-color-scheme: dark) {}` in addition to `[data-theme='dark'] {}`. If necessary that is. (out of scope for this PR)
3. We have two different button components. One sitting at the root of the components directory and another inside atoms. We might be at a place where we merge the root button component and officially diverge from compound? 
4. Accordion feedback is related to the above. However, accordion needs to be refactored in general to use the tokens established in this repo instead of `$space` variables. (out of scope for this PR)
5. Icons are building for me but `accent-high` isn't correct. It's filling the icons with the same color as the background. I THINK we should just ditch the 
```@media (prefers-color-scheme: dark) {
      fill: clr(accent-high);
    }``` 
    and replace with `fill: clr(text-inverse);` - that should at least get them to be visible for both light/dark settings.

**Review by callinmullaney — APPROVED** [review]
Documented issues look good and should unblock this PR from being merged as we can address this feedback later. :shipit:

**Pull request merged**
