### PR TITLE
feat: Refine stories and remove unused CSS functions/mixins

### PR DESCRIPTION
**Pull request by callinmullaney**
## Summary

This PR fixes/implements the following **bugs/features**

* Bug 1
* Bug 2
* Feature 1
* Feature 2
* Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

## Documentation update (required)
If this pull request requires a change to Emulsify documentation, those changes, updates, and/or new information must accompany this pull request.

## How to review this pull request

* [ ] Step 1
* [ ] Step 2
* [ ] Step 3: Profit

## Closing issues

Closes #

### CODE REVIEW

**Review by mariannuar — COMMENTED** [review]
Hi @callinmullaney !

I just finished reviewing everything. Most of all the components look great. I fixed some things in some of them and there are other things that I couldn't fix because of time and because I have some questions. Here's the list of things I found or have questions for:

Storybook UI:
- New storybook version popup message's background and text have color contrast issues
Screenshot 2024-09-27 at 12 54 29 PM

**Accordion:**
- Default and hover states in accordion item icon (when accordion item is closed and open)
- The icons are different compared to what’s in the design. Is this expected?

**Announcement**
- Icon is not being displayed, is this expected?

**Card:**
- Image is missing, is this expected?
Screenshot 2024-09-27 at 12 54 45 PM

**Typography:**
- There isn’t a link-color-inverse token for links with dark backgrounds
Screenshot 2024-09-27 at 1 01 35 PM

**Main Menu:**
- Icons are not being displayed or their color is not being updated?
Screenshot 2024-09-27 at 1 00 21 PM
Screenshot 2024-09-27 at 1 00 28 PM


**Breadcrumbs:**
- Icons are different compared to what’s in the design

**Tokens:**
- The alignment in some tokens
Screenshot 2024-09-27 at 12 54 36 PM

**Logo is missing**

**Comment by joetower** [comment]
@mariannuar I addressed all of your feedback except for this one: 

> Storybook UI:
>
>   New storybook version popup message's background and text have color contrast issues
>    Screenshot 2024-09-27 at 12 54 29 PM


The components should be ready for another look, please. 

@callinmullaney I feel as though the Storybook UI "What's New" contrast issues are caused by inline CSS. I'm looking through documentation wondering if these colors are customizable in Storybook config, but not immediately finding anything. Could this be caused by our Storybook custom theming? Any ideas how to resolve it?

**Comment by callinmullaney** [comment]
@joetower Ya those color contrast issues are coming from Emulsify Core's default theme. https://github.com/emulsify-ds/emulsify-core/blob/develop/.storybook/emulsifyTheme.js - I originally ported this over from an attempt Randy made a year or two ago and admittedly haven't spent any time on it. 

Roberto, MikeG, and I have been looking into ways to implement overrides for this Storybook theme on a per-project basis but ran into an asset loading bug from storybook itself. We're working to resolve it so our only option now is to refine Emulsify Core's theme.

**Comment by joetower** [comment]
@callinmullaney Got it, thanks! I'll take a look at the theme in Core and open a separate PR there. :+1:

**Review by mariannuar — APPROVED** [review]
@joetower Thank you for the work you did, everything works and looks better! @callinmullaney I'm approving this PR 🥳

**Comment by callinmullaney** [comment]
Thank you @mariannuar !

**Pull request merged**
